### ISSUE TITLE
fails to build with ghc-9.12.2

### ISSUE THREAD

**Issue by juhp** [juhp/simple-cabal#2]
```
       /home/curators/work/unpack-dir/unpacked/simple-cabal-0.1.3.1-c0d93525a7e284def2ffcad4febaca1853f0136d57a85f64e248c18b38791e1f/SimpleCabal.hs:215:28: error: [14:19:57 [111/885210]
           • Couldn't match type: Maybe                                                     
                                    (Distribution.Utils.Path.SymbolicPath                                                                                                                
                                       Distribution.Utils.Path.CWD                                                                                                                       
                                       (Distribution.Utils.Path.Dir Distribution.Utils.Path.Pkg))                                                                                        
                            with: [Char]                                                    
             Expected: FilePath -> IO GenericPackageDescription                             
               Actual: Maybe                  
                         (Distribution.Utils.Path.SymbolicPath                              
                            Distribution.Utils.Path.CWD                                     
                            (Distribution.Utils.Path.Dir Distribution.Utils.Path.Pkg))                                                                                                   
                       -> Distribution.Utils.Path.SymbolicPath                              
                            Distribution.Utils.Path.Pkg Distribution.Utils.Path.File                                                                                                     
                       -> IO GenericPackageDescription                                      
           • Probable cause: ‘readGenericPackageDescription’ is applied to too few arguments                                                                                             
             In the second argument of ‘(>>=)’, namely                                      
               ‘readGenericPackageDescription normal’                                       
             In a stmt of a 'do' block:                                                     
               gpd <- findCabalFile >>= readGenericPackageDescription normal                                                                                                             
             In the expression:               
               do gpd <- findCabalFile >>= readGenericPackageDescription normal                                                                                                          
                  return $ package $ packageDescription gpd                                 
           |                                  
       215 |   gpd <- findCabalFile >>= readGenericPackageDescription normal                                                                                                             
           |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                             
                                              
       /home/curators/work/unpack-dir/unpacked/simple-cabal-0.1.3.1-c0d93525a7e284def2ffcad4febaca1853f0136d57a85f64e248c18b38791e1f/SimpleCabal.hs:254:3: error: [GHC-83865]
           • Couldn't match expected type: IO GenericPackageDescription                                                                                                                  
                         with actual type: Distribution.Utils.Path.SymbolicPath                                                                                                          
                                             Distribution.Utils.Path.Pkg Distribution.Utils.Path.File                                                                                    
                                           -> IO GenericPackageDescription                                                                                                               
           • Probable cause: ‘readGenericPackageDescription’ is applied to too few arguments                                                                                             
             In the first argument of ‘(>>=)’, namely                                       
               ‘readGenericPackageDescription normal cabalfile’                             
             In the expression:               
               readGenericPackageDescription normal cabalfile                               
                 >>= makeFinalPackageDescription flags                                      
             In an equation for ‘readFinalPackageDescription’:                              
                 readFinalPackageDescription flags cabalfile                                
                   = readGenericPackageDescription normal cabalfile                                                                                                                      
                       >>= makeFinalPackageDescription flags                                
           |                                  
       254 |   readGenericPackageDescription normal cabalfile >>=                           
           |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^         
```
and more

**Comment by juhp** [comment]
Should be fixed with 0.2.0
