### ISSUE TITLE
fails to build with Cabal-3.8

### ISSUE THREAD

**Issue by juhp** [juhp/simple-cabal#1]
```
Building library for simple-cabal-0.1.3..
[1 of 1] Compiling SimpleCabal

/var/stackage/work/unpack-dir/unpacked/simple-cabal-0.1.3-b865dfac9d0cdcb002ac184fe3f7c2e904d2f7ba8ef1fd61f7c3f36b8cbce23f/SimpleCab
al.hs:123:9: error:
    Module
    ‘Distribution.PackageDescription.Parsec’
    does not export
    ‘readGenericPackageDescription’
    |
123 |        (readGenericPackageDescription, parseGenericPackageDescriptionMaybe)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by juhp** [comment]
Fixed in 0.1.3.1
